import { useEffect, useMemo, useState } from 'react'
import InputField from '../common/InputField'
import { calculateRemainingSessions } from '../../utils/patient'
import { formatPhone, validatePatientForm } from '../../utils/validators'

const empty = {
  name:'', socialName:'', birthDate:'', cpf:'', cns:'', sex:'', genderIdentity:'', status:'active',
  phone:'', secondaryPhone:'', email:'', address:'', addressNumber:'', complement:'', district:'', city:'', state:'', postalCode:'',
  guardian:'', guardianCpf:'', guardianRelationship:'', guardianPhone:'', guardianEmail:'', emergencyName:'', emergencyRelationship:'', emergencyPhone:'',
  diagnosis:'', diagnosticHypothesis:'', complaint:'', referralSource:'', notes:'', allergies:'', medications:'', aspirationRisk:false, tracheostomy:false, gastrostomy:false, oxygenUse:false, epilepsy:false, dietaryRestrictions:'', mobilityRestrictions:'', otherAlerts:'',
  homeCareEnabled:false, sameServiceAddress:true, serviceAddress:'', accessInstructions:'', householdRisks:'', mobilityConditions:'', caregiverName:'', caregiverPhone:'', preferredPeriods:'',
  serviceType:'private', insuranceName:'', registrationNumber:'', sessionValue:'', sessionsPerWeek:1, totalSessions:1, completedSessions:0, paymentNotes:'', professionalName:'', crfa:'', tcleAccepted:false,
}
const list = (value) => (value || []).join?.(', ') || ''

function valuesFrom(patient) {
  if (!patient) return empty
  return { ...empty,
    name:patient.personalData?.fullName || patient.name || '', socialName:patient.personalData?.socialName || '', birthDate:patient.personalData?.birthDate || patient.birthDate || '', cpf:patient.personalData?.cpf || '', cns:patient.personalData?.cns || '', sex:patient.personalData?.sex || '', genderIdentity:patient.personalData?.genderIdentity || '', status:patient.patientStatusV2 || ({Ativo:'active',Inativo:'inactive',Finalizado:'discharged',Arquivado:'archived'}[patient.status]) || 'active',
    phone:patient.contact?.phone || patient.phone || '', secondaryPhone:patient.contact?.secondaryPhone || '', email:patient.contact?.email || '', address:patient.addressV2?.street || (typeof patient.address === 'object' ? patient.address.street : patient.address) || '', addressNumber:patient.addressV2?.number || patient.address?.number || '', complement:patient.addressV2?.complement || patient.address?.complement || '', district:patient.addressV2?.district || patient.address?.district || '', city:patient.addressV2?.city || patient.address?.city || '', state:patient.addressV2?.state || patient.address?.state || '', postalCode:patient.addressV2?.postalCode || patient.address?.postalCode || '',
    guardian:patient.legalRepresentative?.name || patient.guardian || '', guardianCpf:patient.legalRepresentative?.cpf || '', guardianRelationship:patient.legalRepresentative?.relationship || '', guardianPhone:patient.legalRepresentative?.phone || '', guardianEmail:patient.legalRepresentative?.email || '', emergencyName:patient.emergencyContact?.name || '', emergencyRelationship:patient.emergencyContact?.relationship || '', emergencyPhone:patient.emergencyContact?.phone || '',
    diagnosis:patient.clinicalProfile?.diagnosis || patient.diagnosis || '', diagnosticHypothesis:patient.clinicalProfile?.diagnosticHypothesis || '', complaint:patient.clinicalProfile?.mainComplaint || patient.complaint || '', referralSource:patient.clinicalProfile?.referralSource || '', notes:patient.clinicalProfile?.generalObservations || patient.notes || '', allergies:list(patient.clinicalAlerts?.allergies), medications:list(patient.clinicalAlerts?.medications), aspirationRisk:!!patient.clinicalAlerts?.aspirationRisk, tracheostomy:!!patient.clinicalAlerts?.tracheostomy, gastrostomy:!!patient.clinicalAlerts?.gastrostomy, oxygenUse:!!patient.clinicalAlerts?.oxygenUse, epilepsy:!!patient.clinicalAlerts?.epilepsy, dietaryRestrictions:list(patient.clinicalAlerts?.dietaryRestrictions), mobilityRestrictions:list(patient.clinicalAlerts?.mobilityRestrictions), otherAlerts:list(patient.clinicalAlerts?.otherAlerts),
    homeCareEnabled:!!patient.homeCare?.enabled, sameServiceAddress:patient.homeCare?.serviceAddressSameAsPatientAddress !== false, serviceAddress:patient.homeCare?.serviceAddress?.street || '', accessInstructions:patient.homeCare?.accessInstructions || '', householdRisks:list(patient.homeCare?.householdRisks), mobilityConditions:patient.homeCare?.mobilityConditions || '', caregiverName:patient.homeCare?.caregiverName || '', caregiverPhone:patient.homeCare?.caregiverPhone || '', preferredPeriods:list(patient.homeCare?.preferredPeriods),
    serviceType:patient.administrative?.serviceType || 'private', insuranceName:patient.administrative?.insuranceName || '', registrationNumber:patient.administrative?.registrationNumber || '', sessionValue:patient.administrative?.sessionValue ?? '', totalSessions:patient.administrative?.contractedSessions ?? patient.totalSessions ?? 1, completedSessions:patient.administrative?.completedSessions ?? patient.completedSessions ?? 0, paymentNotes:patient.administrative?.paymentNotes || '', sessionsPerWeek:patient.sessionsPerWeek ?? 1, professionalName:patient.professionalName || '', crfa:patient.crfa || '', tcleAccepted:!!patient.tcleAccepted,
  }
}

const Section = ({ title, children }) => <fieldset className="md:col-span-2 grid grid-cols-1 gap-4 rounded-xl border border-noble-200 p-4 dark:border-noble-700 md:grid-cols-2"><legend className="px-2 text-sm font-bold text-plum-700 dark:text-plum-300">{title}</legend>{children}</fieldset>
const Check = ({ name, label, values, setValues }) => <label className="flex items-center gap-2 text-sm text-noble-700 dark:text-noble-300"><input type="checkbox" checked={!!values[name]} onChange={(e)=>setValues((v)=>({...v,[name]:e.target.checked}))}/>{label}</label>

export default function PatientFormModal({ isOpen, onClose, onSubmit, loading, patient }) {
  const [values,setValues]=useState(empty); const [errors,setErrors]=useState({})
  useEffect(()=>{ setValues(valuesFrom(patient)); setErrors({}) },[patient,isOpen])
  const change=(e)=>{const {name,value}=e.target;setValues(v=>({...v,[name]:name.toLowerCase().includes('phone')?formatPhone(value):value}))}
  const input=(label,name,props={})=><InputField label={label} name={name} value={values[name]} onChange={change} error={errors[name]} {...props}/>
  const remaining=useMemo(()=>calculateRemainingSessions(values.totalSessions,values.completedSessions),[values.totalSessions,values.completedSessions])
  const submit=(e)=>{e.preventDefault();const next=validatePatientForm({...values,guardian:values.guardian||'NÃ£o informado',address:values.address||'NÃ£o informado',phone:values.phone||'(00) 00000-0000',birthDate:values.birthDate||'2000-01-01',professionalName:values.professionalName||'NÃ£o informado',crfa:values.crfa||'NÃ£o informado'}); delete next.guardian; delete next.address; delete next.phone; delete next.birthDate; delete next.professionalName; delete next.crfa; if(!values.name.trim())next.name='Informe o nome completo.'; setErrors(next); if(!Object.keys(next).length)onSubmit(values)}
  if(!isOpen)return null
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[95vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-noble-900"><div className="mb-6 flex justify-between"><h3 className="text-xl font-bold dark:text-white">{patient?'Editar paciente':'Novo paciente'}</h3><button type="button" onClick={onClose}>Fechar</button></div><form onSubmit={submit} className="grid grid-cols-1 gap-4 md:grid-cols-2">
    <Section title="1. IdentificaÃ§Ã£o">{input('Nome completo','name',{required:true})}{input('Nome social','socialName')}{input('Data de nascimento','birthDate',{type:'date'})}{input('CPF','cpf')}{input('CNS','cns')}{input('Sexo','sex')}{input('Identidade de gÃªnero','genderIdentity')}<label className="flex flex-col gap-1 text-sm">Status<select name="status" value={values.status} onChange={change} className="rounded-xl border p-2.5 dark:bg-noble-800"><option value="active">Ativo</option><option value="inactive">Inativo</option><option value="discharged">Alta</option><option value="archived">Arquivado</option></select></label></Section>
    <Section title="2. Contatos">{input('Telefone','phone')}{input('Telefone secundÃ¡rio','secondaryPhone')}{input('E-mail','email',{type:'email'})}</Section>
    <Section title="3. EndereÃ§o">{input('CEP','postalCode')}{input('Logradouro','address')}{input('NÃºmero','addressNumber')}{input('Complemento','complement')}{input('Bairro','district')}{input('Cidade','city')}{input('UF','state')}</Section>
    <Section title="4. ResponsÃ¡vel legal">{input('Nome','guardian')}{input('CPF','guardianCpf')}{input('Parentesco','guardianRelationship')}{input('Telefone','guardianPhone')}{input('E-mail','guardianEmail',{type:'email'})}</Section>
    <Section title="5. Contato de emergÃªncia">{input('Nome','emergencyName')}{input('RelaÃ§Ã£o','emergencyRelationship')}{input('Telefone','emergencyPhone')}</Section>
    <Section title="6. Perfil clÃ­nico">{input('DiagnÃ³stico','diagnosis',{type:'textarea'})}{input('HipÃ³tese diagnÃ³stica','diagnosticHypothesis',{type:'textarea'})}{input('Queixa principal','complaint',{type:'textarea'})}{input('Origem do encaminhamento','referralSource')}{input('ObservaÃ§Ãµes gerais','notes',{type:'textarea'})}</Section>
    <Section title="7. Alertas clÃ­nicos"><div className="md:col-span-2 grid gap-3 sm:grid-cols-3">{['aspirationRisk,Risco de aspiraÃ§Ã£o','tracheostomy,Traqueostomia','gastrostomy,Gastrostomia','oxygenUse,Uso de oxigÃªnio','epilepsy,Epilepsia'].map(x=>{const [n,l]=x.split(',');return <Check key={n} name={n} label={l} values={values} setValues={setValues}/>})}</div>{input('Alergias (separadas por vÃ­rgula)','allergies')}{input('Medicamentos relevantes','medications')}{input('RestriÃ§Ãµes alimentares','dietaryRestrictions')}{input('RestriÃ§Ãµes de mobilidade','mobilityRestrictions')}{input('Outros alertas','otherAlerts')}</Section>
    <Section title="8. Home care"><Check name="homeCareEnabled" label="Atendimento domiciliar habilitado" values={values} setValues={setValues}/>{values.homeCareEnabled&&<><Check name="sameServiceAddress" label="Usar o endereÃ§o principal" values={values} setValues={setValues}/>{!values.sameServiceAddress&&input('EndereÃ§o de atendimento','serviceAddress')}{input('InstruÃ§Ãµes de acesso','accessInstructions')}{input('Riscos no domicÃ­lio','householdRisks')}{input('CondiÃ§Ãµes de mobilidade','mobilityConditions')}{input('Cuidador','caregiverName')}{input('Telefone do cuidador','caregiverPhone')}{input('PerÃ­odos preferidos','preferredPeriods')}</>}</Section>
    <Section title="9. Dados administrativos"><label className="flex flex-col gap-1 text-sm">Tipo de atendimento<select name="serviceType" value={values.serviceType} onChange={change} className="rounded-xl border p-2.5 dark:bg-noble-800"><option value="private">Particular</option><option value="insurance">ConvÃªnio</option><option value="institution">InstituiÃ§Ã£o</option><option value="other">Outro</option></select></label>{input('ConvÃªnio','insuranceName')}{input('MatrÃ­cula','registrationNumber')}{input('Valor da sessÃ£o','sessionValue',{type:'number',min:0})}{input('SessÃµes por semana','sessionsPerWeek',{type:'number',min:1})}{input('Total contratado','totalSessions',{type:'number',min:0})}{input('SessÃµes realizadas','completedSessions',{type:'number',min:0})}<div className="rounded-xl bg-gold-100 p-3 text-sm">Restantes: <strong>{remaining}</strong></div>{input('ObservaÃ§Ãµes de pagamento','paymentNotes',{type:'textarea'})}{input('Profissional responsÃ¡vel','professionalName')}{input('CRFa','crfa')}<Check name="tcleAccepted" label="Consentimento/TCLE registrado" values={values} setValues={setValues}/></Section>
    <div className="md:col-span-2 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-5 py-2.5">Cancelar</button><button disabled={loading} className="rounded-lg bg-plum-600 px-5 py-2.5 font-semibold text-white disabled:opacity-60">{loading?'Salvando...':'Salvar'}</button></div>
  </form></div></div>
}
