import { useEffect,useState } from 'react'
import toast from 'react-hot-toast'
import InputField from '../common/InputField'
import { changeScheduleStatus,rescheduleAppointment } from '../../services/scheduleService'
import { allowedTransitions,appointmentStatusToV2 } from '../../domain/appointments/appointmentTransitions'

const labels={scheduled:'Agendado',confirmed:'Confirmado',in_transit:'Em deslocamento',arrived:'Chegou',completed:'Realizado',patient_absent:'Falta',cancelled_by_patient:'Cancelado pelo paciente',cancelled_by_professional:'Cancelado pela profissional',rescheduled:'Reagendado'}
const reasonRequired=new Set(['patient_absent','cancelled_by_patient','cancelled_by_professional','rescheduled'])
export default function ScheduleStatusModal({isOpen,onClose,schedule,userId}){
  const [status,setStatus]=useState('confirmed');const [reason,setReason]=useState('');const [date,setDate]=useState('');const [startTime,setStartTime]=useState('');const [endTime,setEndTime]=useState('');const [saving,setSaving]=useState(false)
  const current=appointmentStatusToV2(schedule?.appointmentStatusV2||schedule?.status);const options=allowedTransitions[current]||[]
  useEffect(()=>{if(!schedule)return;const first=(allowedTransitions[appointmentStatusToV2(schedule.appointmentStatusV2||schedule.status)]||[])[0]||'';setStatus(first);setReason('');setDate(schedule.date||'');setStartTime(schedule.startTime||'');setEndTime(schedule.endTime||'')},[schedule,isOpen])
  const submit=async(event)=>{event.preventDefault();if(!status)return;if(reasonRequired.has(status)&&!reason.trim()){toast.error('Informe o motivo da alteraÃ§Ã£o.');return}if(status==='rescheduled'&&(!date||!startTime||!endTime||endTime<=startTime)){toast.error('Informe uma nova data com horÃ¡rio final posterior ao inicial.');return}try{setSaving(true);const operationId=crypto.randomUUID();if(status==='rescheduled')await rescheduleAppointment(schedule.id,{patientId:schedule.patientId,actorId:userId,operationId,date,startTime,endTime,reason:reason.trim()});else await changeScheduleStatus(schedule.id,schedule.patientId,{status,actorId:userId,operationId,reason:reason.trim()});toast.success('Status atualizado com histÃ³rico preservado.');onClose()}catch(error){console.error(error);toast.error(error.message||'Erro ao atualizar o atendimento.')}finally{setSaving(false)}}
  if(!isOpen||!schedule)return null
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl dark:bg-noble-900"><div className="mb-5 flex justify-between"><div><h3 className="font-bold dark:text-white">Alterar status</h3><p className="text-xs text-noble-500">{schedule.patientName}</p></div><button onClick={onClose}>Fechar</button></div>{options.length===0?<p role="status" className="rounded-xl bg-noble-100 p-4 text-sm dark:bg-noble-800 dark:text-white">Este atendimento estÃ¡ em estado terminal e nÃ£o pode ser reaberto.</p>:<form onSubmit={submit} className="space-y-4"><label className="flex flex-col gap-1 text-sm dark:text-white">Novo status<select value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded-xl border p-2.5 dark:bg-noble-800">{options.map((value)=><option key={value} value={value}>{labels[value]}</option>)}</select></label>{reasonRequired.has(status)&&<InputField label="Motivo" type="textarea" value={reason} onChange={(e)=>setReason(e.target.value)} required/>}{status==='rescheduled'&&<div className="space-y-3 rounded-xl border p-4"><InputField label="Nova data" type="date" value={date} onChange={(e)=>setDate(e.target.value)} required/><div className="grid grid-cols-2 gap-3"><InputField label="Novo inÃ­cio" type="time" value={startTime} onChange={(e)=>setStartTime(e.target.value)} required/><InputField label="Novo fim" type="time" value={endTime} onChange={(e)=>setEndTime(e.target.value)} required/></div></div>}<p className="text-xs text-noble-500">Somente a conclusÃ£o do atendimento debita uma sessÃ£o. A operaÃ§Ã£o e o ator serÃ£o registrados.</p><button disabled={saving} className="w-full rounded-xl bg-plum-600 p-3 font-bold text-white disabled:opacity-50">{saving?'Salvando...':'Confirmar alteraÃ§Ã£o'}</button></form>}</div></div>
}
