import { auth } from '../firebase/config'
async function authorized(path,options={}){const token=await auth.currentUser?.getIdToken();if(!token)throw new Error('Usuário não autenticado.');const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message||'Operação documental não concluída.');return data}
export async function listDocumentMetadata(patientId){const result=await authorized('/api/documents/list',{method:'POST',body:JSON.stringify({patientId})});return result.documents}
export function subscribeDocumentMetadata(patientId,callback,onError){let active=true;const refresh=async()=>{try{const documents=await listDocumentMetadata(patientId);if(active)callback(documents)}catch(error){if(active)onError?.(error)}};void refresh();const interval=setInterval(refresh,5000);return()=>{active=false;clearInterval(interval)}}
export async function requestUpload({patientId,file,category='other',title=file.name,description=null,documentDate=null,sensitivityLevel='sensitive',accessLevel='owner_only',requestId=crypto.randomUUID()}){return authorized('/api/documents/request-upload',{method:'POST',body:JSON.stringify({patientId,requestId,category,title,description,documentDate,sensitivityLevel,accessLevel,originalFileName:file.name,declaredMimeType:file.type,size:file.size})})}
export async function finalizeUpload({patientId,documentId,uploadId,requestId=crypto.randomUUID()}){return authorized('/api/documents/finalize-upload',{method:'POST',body:JSON.stringify({patientId,documentId,uploadId,requestId})})}
export async function uploadFileToQuarantine({authorization,file,onProgress}){const headers=authorization.requiredHeaders||{};if(onProgress)onProgress(10);const response=await fetch(authorization.uploadUrl,{method:'PUT',headers,body:file});if(!response.ok)throw new Error('Falha no envio para a quarentena.');if(onProgress)onProgress(80)}
export async function secureUpload(patientId,file,onProgress){const authorization=await requestUpload({patientId,file});await uploadFileToQuarantine({authorization,file,onProgress});const result=await finalizeUpload({patientId,documentId:authorization.documentId,uploadId:authorization.uploadId});if(onProgress)onProgress(100);return{id:authorization.documentId,name:file.name,type:file.type,size:file.size,status:result.status,available:result.available}}
export async function requestDownload({patientId,documentId,requestId=crypto.randomUUID(),clinicalAttachment=false}){const path=clinicalAttachment?'/api/clinical-attachments/download':'/api/documents/request-download';return authorized(path,{method:'POST',body:JSON.stringify({patientId,documentId,requestId})})}
export async function getDocumentMetadata(patientId,documentId){return authorized(`/api/documents/${encodeURIComponent(documentId)}/status?patientId=${encodeURIComponent(patientId)}`,{method:'GET'})}
export const getSecurityScanStatus=async(patientId,documentId)=>(await getDocumentMetadata(patientId,documentId)).scanStatus
export const validateFileAccess=async(patientId,documentId)=>(await getDocumentMetadata(patientId,documentId)).available===true
export const documentStorageService={requestUpload,finalizeUpload,getDocumentMetadata,listDocumentMetadata,requestDownload,validateFileAccess,getSecurityScanStatus}
