import { describe,expect,it } from 'vitest'
import { registerConsent,revokeConsent,validateConsent } from './consentWorkflow'

function repo(){const docs=new Map([['patients/p',{userId:'u',organizationId:'org'}]]);let id=0;return{docs,createId:()=>`generated-${++id}`,timestamp:()=>new Date(),read:async(path)=>docs.get(path)||null,list:async(patientId)=>[...docs].filter(([path])=>path.startsWith(`patients/${patientId}/consents/`)).map(([path,value])=>({id:path.split('/').at(-1),...value})),recordAudit:async(event)=>{docs.set(`auditLogs/validation-${++id}`,event)},runTransaction:async(callback)=>callback({readMany:async(paths)=>paths.map((path)=>docs.get(path)||null),create:(path,value)=>{if(docs.has(path))throw new Error('exists');docs.set(path,value)},update:(path,value)=>docs.set(path,{...docs.get(path),...value}),set:(path,value)=>docs.set(path,value)})}}
const payload={patientId:'p',requestId:'request-register',consentType:'image',legalBasis:{code:'consent',justification:'Autorização específica para imagem.'},version:{number:1,title:'Uso de imagem v1',hash:'a'.repeat(64)},acceptedMethod:'electronic_checkbox',acceptedEvidence:{summary:'Aceite confirmado.',representativeName:null,representativeRelationship:null}}
describe('consent backend workflow',()=>{
  it('registra aceite, auditoria e idempotência',async()=>{const repository=repo();const first=await registerConsent({uid:'u',payload,repository});const replay=await registerConsent({uid:'u',payload,repository});expect(first.replayed).toBe(false);expect(replay).toEqual({consentId:first.consentId,replayed:true});expect([...repository.docs.keys()].some((key)=>key.startsWith('auditLogs/'))).toBe(true)})
  it('revoga sem apagar histórico e audita',async()=>{const repository=repo();const registered=await registerConsent({uid:'u',payload,repository});const result=await revokeConsent({uid:'u',payload:{patientId:'p',consentId:registered.consentId,requestId:'request-revoke',reason:'Paciente retirou a autorização.'},repository});expect(result.replayed).toBe(false);expect(repository.docs.get(`patients/p/consents/${registered.consentId}`).active).toBe(false)})
  it('valida a versão ativa mais recente e audita',async()=>{const repository=repo();await registerConsent({uid:'u',payload,repository});await registerConsent({uid:'u',payload:{...payload,requestId:'request-v2',version:{...payload.version,number:2,hash:'b'.repeat(64)}},repository});const result=await validateConsent({uid:'u',payload:{patientId:'p',consentType:'image',requestId:'request-validate'},repository});expect(result.valid).toBe(true);expect(result.version.number).toBe(2);expect([...repository.docs.values()].some((item)=>item.action==='consent.validated')).toBe(true)})
  it('nega paciente de outro profissional',async()=>{await expect(registerConsent({uid:'other',payload,repository:repo()})).rejects.toMatchObject({code:'FORBIDDEN'})})
})
