import { randomUUID } from 'node:crypto';import { getFirestore,FieldValue } from 'firebase-admin/firestore';import { getStorage } from 'firebase-admin/storage';import { getEvolutionAdminApp } from './evolutionFinalizeFirebase.js';import { getAuth } from 'firebase-admin/auth'
export async function authenticateDocumentRequest(token){const decoded=await getAuth(getEvolutionAdminApp()).verifyIdToken(token,true);if(!decoded?.uid)throw new Error('unauthenticated');return{uid:decoded.uid}}
export function createDocumentStorageRepository(){const db=()=>getFirestore(getEvolutionAdminApp());const bucket=()=>{const app=getEvolutionAdminApp();const bucketName=process.env.FIREBASE_STORAGE_BUCKET||`${app.options.projectId}.appspot.com`;return getStorage(app).bucket(bucketName)};return{
  createId(path){return db().collection(path).doc().id},randomName(extension){return`${randomUUID()}.${extension}`},timestamp(){return FieldValue.serverTimestamp()},
  async authorizeUpload({storagePath,declaredMimeType,expiresAt}){const[url]=await bucket().file(storagePath).getSignedUrl({version:'v4',action:'write',expires:expiresAt,contentType:declaredMimeType,extensionHeaders:{'x-goog-if-generation-match':'0'}});return{url,requiredHeaders:{'Content-Type':declaredMimeType,'x-goog-if-generation-match':'0'}}},
  async inspectObject(storagePath){const file=bucket().file(storagePath);const[exists]=await file.exists();if(!exists)return null;const[[metadata],[buffer]]=await Promise.all([file.getMetadata(),file.download()]);return{buffer,metadata}},
  async promote({sourcePath,targetPath}){const source=bucket().file(sourcePath);await source.copy(bucket().file(targetPath),{preconditionOpts:{ifGenerationMatch:0}});const[buffer]=await bucket().file(targetPath).download();return buffer},
  async remove(storagePath){await bucket().file(storagePath).delete({ignoreNotFound:true})},
  async signDownload({storagePath,expiresAt}){const[url]=await bucket().file(storagePath).getSignedUrl({version:'v4',action:'read',expires:expiresAt});return url},
  async read(path){const snapshot=await db().doc(path).get();return snapshot.exists?snapshot.data():null},
  async listDocuments(patientId){const snapshot=await db().collection(`patients/${patientId}/documents`).get();return snapshot.docs.map((item)=>({id:item.id,value:item.data()}))},
  runTransaction(callback){const database=db();return database.runTransaction(async(native)=>callback({async readMany(paths){const snapshots=await Promise.all(paths.map((path)=>native.get(database.doc(path))));return snapshots.map((item)=>item.exists?item.data():null)},create(path,value){native.create(database.doc(path),value)},update(path,value){native.update(database.doc(path),value)},set(path,value){native.set(database.doc(path),value)}}))},
}}
