import { useCallback, useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { clinicalAttachmentService } from '../../services/clinicalAttachmentService.js'
import ClinicalAttachmentDetailsDialog from './ClinicalAttachmentDetailsDialog.jsx'
import ClinicalAttachmentList from './ClinicalAttachmentList.jsx'
import ClinicalAttachmentUploadDialog from './ClinicalAttachmentUploadDialog.jsx'

export default function ClinicalAttachmentsTab({ patient }) {
  const[attachments,setAttachments]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[showArchived,setShowArchived]=useState(false);const[uploadOpen,setUploadOpen]=useState(false);const[selected,setSelected]=useState(null);const[options,setOptions]=useState({evolutions:[],appointments:[]});const[uploading,setUploading]=useState(false);const[progress,setProgress]=useState(0);const[downloadingId,setDownloadingId]=useState(null);const[archiving,setArchiving]=useState(false)
  const load=useCallback(async()=>{if(!patient?.id)return;setLoading(true);setError('');try{setAttachments(await clinicalAttachmentService.listPatientAttachments(patient.id,showArchived))}catch(loadError){setError(loadError.message)}finally{setLoading(false)}},[patient?.id,showArchived])
  useEffect(()=>{void load()},[load])
  const openUpload=async()=>{setUploadOpen(true);try{setOptions(await clinicalAttachmentService.listAttachmentLinkOptions(patient.id))}catch(optionError){toast.error(optionError.message)}}
  const submit=async(metadata,file)=>{setUploading(true);setProgress(0);try{await clinicalAttachmentService.createAndUploadAttachment({patientId:patient.id,metadata,file,onProgress:setProgress});toast.success('Anexo processado e vinculado com segurança.');setUploadOpen(false);await load()}finally{setUploading(false);setProgress(0)}}
  const download=async(attachment)=>{setDownloadingId(attachment.id);try{const result=await clinicalAttachmentService.requestDownload(patient.id,attachment.id);window.open(result.downloadUrl,'_blank','noopener,noreferrer')}catch(downloadError){toast.error(downloadError.message)}finally{setDownloadingId(null)}}
  const archive=async(attachment,reason)=>{setArchiving(true);try{await clinicalAttachmentService.archiveAttachment({patientId:patient.id,documentId:attachment.id,reason});toast.success('Anexo arquivado.');await load()}finally{setArchiving(false)}}
  return <section className="space-y-5 pb-6" aria-labelledby="clinical-attachments-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="clinical-attachments-title" className="text-lg font-bold text-noble-800 dark:text-white">Documentos</h3><p className="text-sm text-noble-500">Anexos clínicos protegidos por quarentena, consentimento e auditoria.</p></div><button type="button" onClick={openUpload} className="rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white hover:bg-indigo-700 focus:ring-2 focus:ring-indigo-500">Novo anexo</button></div><label className="inline-flex items-center gap-2 text-sm"><input type="checkbox" checked={showArchived} onChange={(event)=>setShowArchived(event.target.checked)}/>Exibir arquivados</label><ClinicalAttachmentList attachments={attachments} loading={loading} error={error} showArchived={showArchived} onDetails={setSelected} onDownload={download} downloadingId={downloadingId}/><ClinicalAttachmentUploadDialog open={uploadOpen} onClose={()=>setUploadOpen(false)} onSubmit={submit} options={options} validateConsent={(category)=>clinicalAttachmentService.validateRequiredConsent(patient.id,category)} uploading={uploading} progress={progress}/><ClinicalAttachmentDetailsDialog attachment={selected} onClose={()=>setSelected(null)} onArchive={archive} archiving={archiving}/></section>
}
